// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjN6CIfVM-_q2IX7Dz15KLS_BhQvDxspg',
    appId: '1:432119244131:web:a4bc1b2fe280292ad59f56',
    messagingSenderId: '432119244131',
    projectId: 'projbab-fb3a6',
    authDomain: 'projbab-fb3a6.firebaseapp.com',
    storageBucket: 'projbab-fb3a6.appspot.com',
    measurementId: 'G-RRGJLTFCRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzg-_4ywdPCr8zFGY5LQPT-xHzb0HW26M',
    appId: '1:432119244131:android:ab3a247024705259d59f56',
    messagingSenderId: '432119244131',
    projectId: 'projbab-fb3a6',
    storageBucket: 'projbab-fb3a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6S3lrDsfY2AK_rGvpNuKwi70L8O795eA',
    appId: '1:432119244131:ios:9b7c4d4ca254c1e4d59f56',
    messagingSenderId: '432119244131',
    projectId: 'projbab-fb3a6',
    storageBucket: 'projbab-fb3a6.appspot.com',
    iosClientId: '432119244131-7r6r3mqa9hispha3k7bntaj4461ka2mj.apps.googleusercontent.com',
    iosBundleId: 'com.teamf5.projectBab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6S3lrDsfY2AK_rGvpNuKwi70L8O795eA',
    appId: '1:432119244131:ios:9b7c4d4ca254c1e4d59f56',
    messagingSenderId: '432119244131',
    projectId: 'projbab-fb3a6',
    storageBucket: 'projbab-fb3a6.appspot.com',
    iosClientId: '432119244131-7r6r3mqa9hispha3k7bntaj4461ka2mj.apps.googleusercontent.com',
    iosBundleId: 'com.teamf5.projectBab',
  );
}
